### ISSUE TITLE
앞으로의 실습 시간에 대한 질문

### ISSUE THREAD

**Issue by postBG** [snu-sf-class/swpp2015fall#10]
안녕하세요. 앞으로의 실습 계획은 어떻게 되나요? 
매주 있는 실습시간 동안 앞으로 매주 무엇을 배울지 궁금합니다.

**Comment by alxest** [comment]
- 아직 확정되지 않았습니다.

- 날짜는 결정되지 않았지만, 다룰 내용은
Coverage testing
Cucumber
Jenkins (Git 할 때 이야기했던)
Refactoring
정도입니다.

- 시간이 남을 것이고, 어떤 내용을 추가로 다룰 지는 교수님과 더 상의해봐야 할 것 같습니다. 변동의 여지가 많습니다. 수업 중에 다뤘던 내용에 맞춰서 연습반 내용이 추가될 여지가 많습니다.

- 일단 제가 생각하고 있는 내용들은
Rails - 페이스북 OAuth 연동, devise 젬을 이용한 간단한 회원가입 시스템 구현 등 실습 / 세션, 쿠키 등 이해 / ORM 더 자세히 등등등등
Heroku 소개
React.js 소개
정도입니다.

- 제안이나 의견 있으시면 자유롭게 주세요.
