### ISSUE TITLE
숙제 제출과 관련한 질문입니다.

### ISSUE THREAD

**Issue by HeeMyung** [snu-sf-class/swpp2015fall#11]
제 계정에 개인 리파지터리 이름을 swpp-Assignment1로 해서 만들어 올렸는데요. 따로 알려드리지 않아도 되는건가요? 아니면 email로 알려드려야 하나요?

**Comment by alxest** [comment]
알려주시지 않으셔도 됩니다. 처음에 구글 설문조사로 깃허브 아이디를 조사해서, 그것을 통해 알 수 있습니다.
감사합니다.
