### ISSUE TITLE
Rails Active Record 관련 질문.md

### ISSUE THREAD

**Issue by postBG** [snu-sf-class/swpp2015fall#12]
안녕하세요.
Rails Active Record와 관련된 질문이 있어 글을 올립니다.
저희는 action에서 Rails가 기본적으로 제공하는 active record를 직접 사용하지 않고 아래와 같이 하기로 했습니다

>데이터베이스의 구조가 프로젝트 중에 변할 수 있어 rails에서 제공하는 Active record함수들을 action에서 직접 사용하지 않고, 데이터베이스에 접근하는 interface(예를 들면, getUserName()과 같은 함수를 만들기로 함)를 만들기로 함

질문은 이런 기능을 구현하기 위해서는 어느 부분에 함수를 만들어야 하나요?
그냥 action같이 controller내부에 만들면 되는 건가요?

**Comment by alxest** [comment]
제가 문제 상황을 제대로 이해하지 못했는데, 데이터베이스 테이블은 고정되있는데 컬럼이 바뀔 수 있는 상황이면 해당 테이블 모델 파일 안에 구현해놓을 것 같습니다. 테이블 자체가 고정되있지 않다면 아마도 컨트롤러 쪽에 구현해야 할 것 같습니다. 이 경우에는 ApplicationController에 구현해서 모든 컨트롤러가 그 함수를 포함하게 할 수도 있을 것이고, 그 함수를 필요로 하는 컨트롤러들만 잘 파악해서 중간 클래스를 만들어서 상속받을 수도 있을 것 같습니다.

어디에 코드를 넣을 것이냐 - 모델? 컨트롤러? - 가 딱 정해진 방법은 없는 것 같습니다. fat model skinny controller 등등 어떤 패러다임이 있고 그걸 지지하는 사람들도 반대하는 사람들도 있는 것 같습니다. 그리고 재사용성을 염두에 둘 때에도 이것을 따로 클래스로 만들 것이냐, 모듈로 만들 것이냐 등 선택지가 있는 것 같습니다. 그때그때 필요성을 느끼면 잘 리팩토링 하는 것이 중요할 것 같습니다.

관련하여 조금 찾아보았는데요, 이런 글들을 참고하시면 도움이 될 듯 합니다.
http://stackoverflow.com/questions/128450/best-practices-for-reusing-code-between-controllers-in-ruby-on-rails
http://stackoverflow.com/questions/1068558/oo-design-in-rails-where-to-put-stuff
http://www.justinweiss.com/articles/where-do-you-put-your-code/
https://richonrails.com/articles/rails-4-code-concerns-in-active-record-models

**Comment by postBG** [comment]
감사합니다. 참고하도록 하겠습니다
