### ISSUE TITLE
[질문] X window를 이용한 Git GUI Tool에 대하여

### ISSUE THREAD

**Issue by HeeMyung** [snu-sf-class/swpp2015fall#13]
콘솔로 git을 다루는게 안 익숙한데 혹시 X window를 통해서 이용할 수 있는 git용 gui tool이 있나요? 있다면 현 수업용 서버에 설치가 가능한가요?

**Comment by alxest** [comment]
저도 잘 모르겠습니다. http://unix.stackexchange.com/questions/48469/gui-for-git-similar-to-sourcetree 이런거 보면 리눅스용으로도 분명히 있는 것 같고 아마 X forwarding 으로 받아보는 것도 될 것 같습니다.
설치를 원하시는게 있으시면 설치해드리겠습니다.
