### ISSUE TITLE
서버로 개발하면서 파이어 폭스말고 크롬을 쓸 수는 없나요?

### ISSUE THREAD

**Issue by postBG** [snu-sf-class/swpp2015fall#4]
그럴 순 없나요?

**Comment by alxest** [comment]
서버에서 레일즈를 실행하실 때 명령어에 -b 0.0.0.0 을 추가하면 외부에서도 접근이 가능할 것입니다.
예를 들어 rails s -b 0.0.0.0 -p 3000 이런 식으로 띄우면
http://147.46.78.35:3000/ 주소로 접근이 가능할 것입니다.
그리고 편한 브라우져로 작업하시면 될 것 같습니다.
