### ISSUE TITLE
bashrc, vimrc 관련 질문

### ISSUE THREAD

**Issue by postBG** [snu-sf-class/swpp2015fall#5]
putty를 실행할 때마다 bashrc와 vimrc에 대한 source를 새로 해주어야 하는데, 
이런 환경설정을 영구적으로 반영하는 방법 없을까요?

**Comment by alxest** [comment]
저는 맥 기본 쉘에서 ssh 명령어로 접속하는데 잘 적용됩니다, 푸티로는 사용해보지 않아서 잘 모르겠습니다 ㅠㅠ
푸티로 다른 서버에 접속할 때는 괜찮았나요?
혹시 푸티를 사용하는 다른 분들도 같은 증상을 겪고 있나요?

**Comment by postBG** [comment]
답변 감사드립니다.
지금까지 실습이나 martini에서는 잘 적용되었던 걸로 기억하는데 다른 분들은 잘 모르겠네요.
