### ISSUE TITLE
Json사용에 관한 질문

### ISSUE THREAD

**Issue by postBG** [snu-sf-class/swpp2015fall#6]
안녕하세요. 전부 만들고 보니 json구조체로 만들긴 했는데 도저히 이 정보를 어디에 보내고 어디서 어떻게 써야할 지를 모르겠습니다. 사실 다른 기능은 전부 구현을 해서 redundant한 거 같은데, 어디에 어떻게 써야하는 건지 알려주실 수 있으신가요?

**Comment by alxest** [comment]
질문의 의미를 잘 모르겠습니다.
"전부 만들고 보니", "사실 다른 기능은 전부 구현을 해서 redundant" -> ?
"어디에 보내고" -> 숙제 스펙의 2. Design: Backend 부분에 명시되어 있습니다. 
"어디서 어떻게 써야할 지" -> 정확히 어떤 문제 상황인지 모르겠습니다. 막연히 모르겠는 (무엇을 모르겠는지 잘 모르는) 상황이라면 튜토리얼 전반을 혼자서 다시 복습해보시는걸 추천드립니다. routes.rb 파일에서 컨트롤러의 메쏘드에 대응시켜주는 부분은 혹시 이해하셨나요?

**Comment by postBG** [comment]
질문이 명확하지 않았던 점 사과드립니다.

그러니까...저의 질문은 저의 구현은 
 Prefix Verb URI Pattern          Controller#Action
     main GET  /main(.:format)      user#main
  welcome GET  /welcome(.:format)   user#welcome
   signup POST /signup(.:format)    user#signup
    login POST /login(.:format)     user#login
   logout POST /logout(.:format)    user#logout
clearData GET  /clearData(.:format) user#clearData
이런 식으로 되어 있고, login버튼을 누르면 login액션이 실행되고 signup버튼을 누르면 signup버튼이 실행되는 식입니다.
문제는 signup 과정을 예를 들어 설명드리면, json 리퀘스트 없이
성공시 => redirect_to "/main"
실패시 => redirect_to :back
과 같이 구현하였습니다.
그런데 json을 사용하려다 보니, 성공시 welcome페이지, 실패시 main페이지를 자동으로 띄우지 못하고, signup페이지에 머물러 있게 됩니다.

이런 경우, 어떻게 해야할 지를 모르겠고, 또 json의 response는 어디에 사용되는 건지도 잘 모르겠다는 뜻이었습니다.

혹시 도움을 조금 주실 수 있으신가요?

**Comment by alxest** [comment]
"login 버튼을 누르면 login액션이 실행"되는 부분을, ajax를 이용하여 구현하고, 리퀘스트를 보내고 돌아온 결과를, ajax의 콜백 함수 부분에서 읽고 해석하여, 적절하게 처리해 주시면 될 듯 합니다.

**Comment by postBG** [comment]
답변 감사드립니다.
하나 더 질문을 드리고 싶은데, 
signup액션에서 
render json:@response를 하게 되면
이 json은 /signup페이지로 가게 되는데, 그러면 여기서 ajax가 이 json object를 받기만 해서 그 값에 따라 
/signup에서 redirect를 적절하게 해주는 방법은 없나요?

**Comment by alxest** [comment]
각 액션마다 render와 redirect 중 최대 하나만 가능한 것으로 알고 있습니다.
프론트 딴에서 JQuery의 load 함수 등을 이용하여 redirect 해주시면 될 것 같습니다.
