### ISSUE TITLE
숙제 질문

### ISSUE THREAD

**Issue by instigation** [snu-sf-class/swpp2015fall#7]
1. Heroku 등의 서비스를 이용하여 Deploy하는 대신 서버에서 tmux/screen 등을 이용하여 띄워놓아도 됩니다. 라고 되어 있는데 이것은 rails 실습때처럼 localhost로만 돌릴 수 있어도 된다는건가요? screen이 terminal 여러개 띄우는 거를 좀 편하게 해주는 프로그램인걸로 알고 있습니다만
2. 
![image](https://cloud.githubusercontent.com/assets/14084546/10261941/63768256-69ed-11e5-90fa-59187304b778.png)
이게 잘 이해가 안 되는데요, response가 json이라는거는 POST /signup 리퀘스트를 받으면 서버가 json만 보내주고 끝내면 되는건가요? 그럼 이거는 메인화면에서 add user하고 log in하는거하고는 상관없어도 되나요? 제가 만든 route는 아래와 같습니다
![rake_routes](https://cloud.githubusercontent.com/assets/14084546/10261951/d8bc44e2-69ed-11e5-8643-a83b5864fd85.PNG)
만약 상관이 있어야 된다면.. response가 서버 내부적인 response를 뜻하는 건가요? 전 예를 들어 GET www.naver.com을 했을 때 뜨는 html페이지가 response인 것으로 알고 있는데 뭔가 잘못 알고 있는건지 설명 부탁드립니다.

**Comment by alxest** [comment]
1. 예, -b 0.0.0.0 옵션을 줘서 밖에서 http://147.46.78.35:3000/ 이런 식으로 접근이 가능하기만 하면 됩니다. 포트는 겹치지 않게 적당히 찾아서 해주시면 되고, Report.pdf 파일에 명시만 해주시면 됩니다. screen/tmux는 터미널 닫아도 돌아가는 상태를 유지하는데 편하라고 언급한 것입니다. 본인이 컴퓨터를 항상 켜놓으신다면 별로 신경쓰지 않으셔도 됩니다.
2. response에 대해서는 말씀하신 부분이 맞는 것 같습니다. add user와 log in 버튼의 행동은 1. Featuers 섹션에 묘사되어 있는데요, add user 버튼이 눌렸을 때 /signup 으로 리퀘스트를 보내고 결과에 따라서 행동하고  log in 버튼이 눌렸을 때 /login 으로 리퀘스트를 보내고 결과에 따라서 행동하게 짜주시면 될 것 같습니다.
제 경우에는 
~~~
~/login-counter-rails $ rake routes
   Prefix Verb URI Pattern          Controller#Action
     root GET  /                    users#index
    login POST /login(.:format)     users#login
   signup POST /signup(.:format)    users#signup
   logout GET  /logout(.:format)    users#logout
clearData POST /clearData(.:format) users#clear_data
~~~
이렇게 구현되어 있습니다.

**Comment by instigation** [comment]
response에 대해서.. 제가 말한 어느 부분이 맞는거죠..? 그러면 add user버튼이 눌리면 POST /signup 리퀘스트가 가고 서버는 json으로 응답을 하는데 그럼 브라우저가 welcome 화면을 어떻게 띄우죠?? 받은건 json object밖에 없는거 아닌가요
그게 아니면 POST /signup을 하면 controller가 view한테 json으로 응답한다 뭐이런건가요?

**Comment by alxest** [comment]
ajax로 리퀘스트를 보내고, ajax 콜백 함수 부분에서 돌아온 json object를 읽고 적절하게 처리해주시면 될 것 같습니다.
"controller가 view한테 json으로 응답"하는 것은 제 이해와는 약간 다른 듯 합니다.

**Comment by instigation** [comment]
ㅠㅠ그러면 rails는 front-end에 속하는 건가요? controller랑 model이 backend이고 view가 frontend인줄 알았는데요

**Comment by alxest** [comment]
저도 말씀하신 것처럼 view가 front-end(html,css,js 등) / controller, model이 backend라고 이해하고 있습니다.
보통 rails는 full stack framework라고 부르는 것으로 알고 있습니다.

**Comment by alxest** [comment]
제 경우에는 app/assets/javascripts 디렉토리의 js (혹은 coffee) 파일에서 해당 기능을 구현해놓았습니다. (기본적으로 application.html.erb에서 로드해줌)
html에서의 버튼 (#login_btn)이 눌리면 ajax를 이용해서 /login으로 리퀘스트를 보냅니다. (http type: post, url: /login, 해당하는 파라미터 넣고, data type: json) 그리고 콜백 함수에서 data["error_code"]를 보고 적절하게 행동합니다.

**Comment by instigation** [comment]
아 그렇군요.. 답변 감사합니다
