### ISSUE TITLE
저희 4일까지 제출해야 하는 Project Requirements and Specifications 발표도 해야하나요?

### ISSUE THREAD

**Issue by instigation** [snu-sf-class/swpp2015fall#8]
저희 4일까지 제출해야 하는 Project Requirements and Specifications 발표도 해야하나요?
ppt를 따로 준비해야 할까요

**Comment by alxest** [comment]
예, 발표 준비도 하셔야 합니다. 공지 파일에 명시해두도록 하겠습니다.

**Comment by alxest** [comment]
작년 자료를 보시면 각 팀에서 pdf 파일과 pptx 파일을 둘 다 제출하신 것을 보실 수 있습니다. 비슷하게 준비하시면 될 듯 합니다.
