### ISSUE TITLE
숙제 질문입니다.

### ISSUE THREAD

**Issue by freor** [snu-sf-class/swpp2015fall#9]
rails에서 ajax를 사용하려고 하는데,
jquery의 $.ajax를 사용할 때 
rails의 controller의 특정 action에 request를 하고싶은데
어떻게 해야하나요?

아니면, rails의 button_to나 link_to 만을 이용해서 ajax를 구현할 수 있나요?

**Comment by alxest** [comment]
ajax를 이용하여 서버의 특정 주소에 http 리퀘스트를 보내고, 서버에서 그 주소로 들어온 리퀘스트를 어떤 controller의 어떤 action에서 처리할 지는 config/routes.rb 에서 정해주는 것으로 알고 있습니다.

**Comment by freor** [comment]
jquery로
$.ajax({
type: "POST",
url: "/login",
dataType: "JSON",
success: function(data){},
error: function(xhr, status, error) {}
});
와 같이 ajax 요청을 하였고

controller에서는
def login
  render json: { "error_code" => -1}
end
로 json response를 하였는데, ajax가 동작하지 않습니다ㅠㅠ
해결방법을 알 수 있을까요...?

**Comment by alxest** [comment]
프린트문 등을 넣어가면서 오류의 범위를 좁혀가봐야 할 것 같습니다.
- ajax가 아닌 다른 방법으로 리퀘스트를 보내면 정상적으로 동작하는지 (chrome postman이나 온라인에서 http 리퀘스트를 보내주는 서비스도 있구요, 아니면 편한 스크립팅 언어로 짜볼 수도)
- ajax로 리퀘스트를 보내기는 하는지 (ajax 관련 코드 직전에 alert()을 넣어본다던지)
이런 식으로 좁혀나가야 할 것 같습니다.

혹시 도움이 될려는지 모르겠지만, 저번 시간의 예제는 (https://github.com/alxest/ajaxTest) 여기 있습니다.

**Comment by HeeMyung** [comment]
해당 주소로 routing이 제대로 되어있는지 확인해 보셨나요?
함수이름이랑 url에 넣어준게 자동으로 매칭되는게 아니니까..

**Comment by freor** [comment]
post 'main/login' => 'main#login' 으로 하였는데 안되네요ㅠㅠ
get 일때는 잘 동작하는데 말이죠..

**Comment by alxest** [comment]
백엔드의 문제인가요? (ajax가 아닌 다른 방법으로 보내도 안되는 경우?)
저라면 
rake routes 치면 라우팅 잘 되있는지 확인
아예 main#login에 진입을 하는지 확인 (루비 코드로 프린트를 찍어도 결과가 나오고, logging 을 따로 해도 되고, 아니면 그냥 셧다운 시켜도 되고 어떤 방식으로든 시작 부분에 코드를 넣어서)
리퀘스트를 보내면 레일즈 띄워놓은 곳에서 메세지가 뭐라고 나오는지 확인
해볼 것 같습니다.

**Comment by HeeMyung** [comment]
엄...
post 'login' => 'main#login' 으로 해야 하는거 아닌가요?
앞에 왜 'main/login'이지

**Comment by freor** [comment]
아아 잘못적엇어요 post 'login'으로 햇어요

**Comment by HeeMyung** [comment]
제가 한거랑 비교해보니 이제 차이가 날만한게 
render json: { "error_code" => -1} -> render json: { :error_code => -1}
정도 밖에 없는거 같네요.. 저것도 아니면 저도 모르겠네요 ㅋㅋ
